apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIELDCCApSgAwIBAgIQARmMizWOU0uYTgbJSDrTTzANBgkqhkiG9w0BAQsFADAv
      MS0wKwYDVQQDEyRmMTBlMjlmOC05MWRkLTQzZDktYWE0ZS1kZjcxNWI2NTY1Nzcw
      IBcNMjYwNDMwMDM1NzAwWhgPMjA1NjA0MjIwNDU3MDBaMC8xLTArBgNVBAMTJGYx
      MGUyOWY4LTkxZGQtNDNkOS1hYTRlLWRmNzE1YjY1NjU3NzCCAaIwDQYJKoZIhvcN
      AQEBBQADggGPADCCAYoCggGBAKo9S66whkJBOZ9LzXjT3ZXNYIuoFzBWYQsbLzc9
      bYIW9mupU7raRlY1rtPoPrsR41HM/SZmMVNJV7RjMeX7plROgcC6dJPIveth6WQV
      p+u0U7GFsHoIh3ruqCYPjJlESQ0/urueBHYa8vDYqp28NaR9SVXr+Q2vMfU9ZI4a
      lFpSOnmkLjrggJlxwE+ZbuOmGVdODy2zrxrUPYRreCMz7tN7XBb2naNdLQtF4rKw
      B1lsg5msyosoNi7kqt7hM/UbFISpPPjBSxWfC0WGU+S+BprSXm0MSpI29tIavpL0
      TUlIxpVY7ZwW+QBIGbLWYctR62BRFymT7eQ+l9oMw6pIjveH1wkwjSj3Hv03dj9f
      SM8MTrXKv8em0uOQo/Anrf0ieWQ8GZMOyw3CoQnIfGNpFG1UNSr2kmO/Cx+qO/Xr
      z6rxhCRDe7x/3OgxrUeb6RRYSxpqAEeKmo2M8r8K9UcZZHbYh2tAlv1CNuoLoO5Q
      dV49+grbeZZDEFA7DnHoLBF0OwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAgQwDwYD
      VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU9ALKmAXp6KdFhAgLofh84KySUeowDQYJ
      KoZIhvcNAQELBQADggGBACDdduEUHcN9TqMibcs9kh0/g7qJn84m6RDNyL7C1wU3
      XUGXqi7QeZj8SfvmgymJupnffRJAGh6vkgHUKGWxceB6qGbMcPWLiJOi0Q5q8UVT
      xGtEkY6vbrJuVVmrnBiNRCwA72l+GVCF373dq6EcqMC0QHXqmLHWBmBwQx/F03+W
      XjpYYQ+6/IvZ4+hbJCjcbXc0ZVmae2gtOzpVIxD8ZN+sV9z7q4uS3g+LJQLUKG/A
      NbE+0fNPYW7geQgrX1OI/OIuJkA0AZwmdeRAmZ0fXQOxb0syT2ZQV6H18ju8Rpx8
      xVKmADKxtC4blj5jeMZy4RtCgO0xgPd99NtKEgWOM8vxwkIQeszXQG6H0RrDMRhE
      kBDQm7BJbP3PWoBaSN5RslTJb/R0JSv7XyJVBUmzikpCvozK4m0rHgPSyRG58E32
      nBX8NEoY3c05My5OjGiVTuamrIFftNihb+Jz76zxtHqEWB0TVA10qKFFj5K3BJKr
      9T51h2Q9SHQtcDQEHrMKLA==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-04-30T05:02:26Z"
    name: kube-root-ca.crt
    namespace: default
    resourceVersion: "1777525346124655024"
    uid: a7e58391-fb50-4c37-a593-c9ccfd7e1d87
- apiVersion: v1
  data:
    ORDER_SERVICE_URL: http://order-service:8080/orders
  kind: ConfigMap
  metadata:
    creationTimestamp: "2026-04-30T05:18:56Z"
    labels:
      app: profile-service
      app.kubernetes.io/managed-by: cloud-console
    name: profile-service-config-mnmn
    namespace: default
    resourceVersion: "1777526336080063022"
    uid: 528543f8-c8c1-4e91-864f-185252437e82
kind: List
metadata:
  resourceVersion: ""
