apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/backends: '{"k8s1-c2b2bca0-default-profile-service-80-c0180018":"HEALTHY","k8s1-c2b2bca0-kube-system-default-http-backend-80-22119107":"HEALTHY"}'
      ingress.kubernetes.io/forwarding-rule: k8s2-fr-m7iivarh-default-profile-ingress-texpvvco
      ingress.kubernetes.io/target-proxy: k8s2-tp-m7iivarh-default-profile-ingress-texpvvco
      ingress.kubernetes.io/url-map: k8s2-um-m7iivarh-default-profile-ingress-texpvvco
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"gce"},"name":"profile-ingress","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"service":{"name":"profile-service","port":{"number":80}}},"path":"/profiles","pathType":"Prefix"},{"backend":{"service":{"name":"profile-service","port":{"number":80}}},"path":"/health","pathType":"Prefix"},{"backend":{"service":{"name":"profile-service","port":{"number":80}}},"path":"/profile-orders","pathType":"Prefix"},{"backend":{"service":{"name":"profile-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
      kubernetes.io/ingress.class: gce
    creationTimestamp: "2026-05-03T02:37:00Z"
    finalizers:
    - networking.gke.io/ingress-finalizer-V2
    generation: 1
    name: profile-ingress
    namespace: default
    resourceVersion: "1777775978263823016"
    uid: 2b7b4c6b-68a7-4e1b-a268-3d5a075ea526
  spec:
    rules:
    - http:
        paths:
        - backend:
            service:
              name: profile-service
              port:
                number: 80
          path: /profiles
          pathType: Prefix
        - backend:
            service:
              name: profile-service
              port:
                number: 80
          path: /health
          pathType: Prefix
        - backend:
            service:
              name: profile-service
              port:
                number: 80
          path: /profile-orders
          pathType: Prefix
        - backend:
            service:
              name: profile-service
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 34.49.193.246
kind: List
metadata:
  resourceVersion: ""
